language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script: yarn run test
notifications:
  slack:
    secure: p4YVO1+uG0b1MgrZDLL6/xib2wAp+o5kh6Y6f+CBkGcKaudFv6wppFOVajZ+mLTfmL2q1MbmZ9qvn+eQ/qf1m0dLnFt2WyFvJR/ugFKLIqg9OHbdzip4gt8vpJpUJRoZQfEwc2aUk6MUfo2wQk1XAujR7wEOwNu+ruK8thotitLyeVvLf+nubSltIBaXZqsf/cc+Us608ocT4wQooEgcC6grYFPkDPo1oBEuKdr9Xzodwz076O6skuLgiG9sj/8485DdIxoy72NnfJ5KfzpOVtsJj3o3kZe/4mhnnwoDtWLxv+fKOQZgLfe9OjmijgaLfnb2AEQ00/ATd1j7Ud6ZbaWrsJkdw5OKznuju4UlRly6UB+uWDSYLi47e5PwvmS6FJnaWw/disNxAy4Bw2mpAPg+ZJ8Ru4sFLybYeqLG7LlT1nVfpw8uNmJjT8GNsD8R6dHSrxHBEz6x1fzSvRCcKYjdEaqDbm3LN8oPNO+EpTbZ3Pp2aUi+ULEL7Pq/CRr/PIM6Yfb+nLeena+8yL/N2FfchVrMh3O08mtHzr1rwuFcVcOupnvTKXjl9q+DRI595CuHHSQ84JXr95xX5nuba3nSa1N65a5H0Nq6b4zXY58+G3ZriY9h2c6vcoh5Li1fVdxt6Sy0UOrjl7kadyDv8lHyehLrV0IWwusvu/k+5bo=
